version: '3.7'
services:
  sonarqube:
    build: ./sonarqube
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    environment: 
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar      
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
  
  db:
    image: postgres:12
    networks:
      - mynetwork
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - pg_data:/var/lib/postgresql/data

  jenkins:
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:443'
      - '50000:50000'
    volumes:
      - ../sample:/opt/app/sampleKt
      - ../sample-react:/opt/app/sampleReact
      - ../sample-multi:/opt/app/sampleMulti
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - PLUGINS_FORCE_UPGRADE=true
    networks:
      - mynetwork
    depends_on:
      - sonarqube

networks:
  mynetwork:

volumes:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_extensions:
  pg_data:
